name: test

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-fast:
    strategy:
      fail-fast: true

    name: Fuzz testing (fast)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'

      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests (fast)
        run: |
          ./run_tests.sh -vvv --fuzz-runs 32
        id: test

  test-slow:
    strategy:
      fail-fast: true

    name: Fuzz testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'

      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: |
          ./run_tests.sh -vvv
        id: test
